apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scientific-tagger-web
  name: scientific-tagger-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    io.kompose.service: scientific-tagger-web
