from project.server.main.sdg.utils import does_contain, does_contain_list

def test_sdg1(asjc_list, ti_abs_kw):
    cond1_0, evidence1_0 = does_contain_list(asjc_list, ["3300","3301","3302","3303","3304","3305","3306","3307","3308","3309","3310","3311","3312","3313","3314","3315","3316","3317","3318","3319","3320","3321","3322","2000","2001","2002","2003"])
    cond_1_1, evidence_1_1 = does_contain(ti_abs_kw, ["poor population","poor households","poorer households","poorest households","the poorest","the poor","poor and marginalized","poor communities","poorer communities","poorest communities","poorer countries","poor countries","poor country","poorest countries","poorer nations","poor nations","poor nation","poorest nations","poor people","poorer people","poorest people","pro-poor","propoor","low-income","the urban poor","the rural poor","urban poor area","rural poor area","poor children","poorer children","poorest children","poor women","poor and needy","poor and vulnerable","poorest and most vulnerable","help the poor","poor village","poor borrower","poor workmanship","poor worker","poor working families"])
    cond1 = cond1_0 and cond_1_1

    cond2_0, evidence2_0 = does_contain(ti_abs_kw, ["social protection","safety net","safety nets","economic resource","food security","cash transfers","food insecurity","development assistance","income inequality","labour market","health insurance","protection system","financial aid","financial development","north-south divide","financial inclusion","women empowerment"])
    cond2_1, evidence2_1 = does_contain(ti_abs_kw, ["poor population","poor households","poorer households","poorest households","the poorest","the poor","poor and marginalized","poor communities","poorer communities","poorest communities","poorer countries","poor countries","poor country","poorest countries","poorer nations","poor nations","poor nation","poorest nations","poor people","poorer people","poorest people","pro-poor","propoor","low-income","the urban poor","the rural poor","urban poor area","rural poor area","poor children","poorer children","poorest children","poor women","poor and needy","poor and vulnerable","poorest and most vulnerable","help the poor","poor village","poor borrower","poor workmanship","poor worker","poor working families"])
    cond2 = cond2_0 and cond2_1

    cond3, evidence_3 = does_contain(ti_abs_kw, ["no poverty","financial literacy","extreme poverty","poverty alleviation","alleviating poverty","alleviation of poverty","poverty alleviating","alleviation in poverty","poverty eradication","eradicating poverty","eradication of poverty","poverty rate","poverty reduction","reduction of poverty","reduction in poverty","reduction of the poverty","reduction of both poverty","reduced poverty","poverty reducing","reduce poverty","end poverty","alleviate poverty","eradicate poverty","protection against poverty","protect against poverty","poverty indice","poverty line","resilience of the poor","financial empowerment","distributional effect","distributional effects","child labor","child labour","development aid","aid the development","Aid for Development","aid in the development","social protection","welfare state","welfare states","state welfare","Social Security","social assistance","system of social protection","systems of social protection","microfinanc","micro-financ","food bank","food banks"])

    if cond1 or cond2 or cond3:
        return {"sdg_code": "sdg1", "sdg_label": "1. No poverty"}
    return {}
