from project.server.main.sdg.utils import does_contain, does_contain_list

def test_sdg5(asjc_list, ti_abs_kw):

    cond1, _ = does_contain(ti_abs_kw, [
        "gender inequality"
,"male-female difference"
,"male-female income difference"
,"gender equality"
,"gender equity"
,"gender inequalities"
,"across gender"
,"gender equalities"
,"employment equity"
,"gender wage gap"
,"female labor force participation"
,"female labour force participation"
,"women labor force participation"
,"women labour force participation"
,"womens' employment"
,"female employment"
,"women's unemployment"
,"female unemployment"
,["access", "family planning services"]
,"forced marriage"
,"spouse Abuse"
,"child marriage"
,"forced marriages"
,"child marriages"
,"occupational segregation"
,"women's empowerment"
,"empowerment of women"
,"women empowerment"
,"girls' empowerment"
,"empowerment of girls"
,"girls empowerment"
,"female empowerment"
,"female genital mutilation"
,"female genital cutting"
,"domestic violence"
,["women", "violence"]
,["girl", "violence"]
,"sexual violence"
,["unpaid work", "gender inequality"]
,["unpaid care work", "gender inequality"]
,"women's political participation"
,"women political participation"
,"female political participation"
,"female managers"
,"women in leadership"
,"female leadership"
,"intra-household allocation"
,["access", "reproductive healthcare"]
,"honour killing"
,"honor killing"
,"honour killings"
,"honor killings"
,"antiwomen"
,"anti-women"
,"feminism"
,"misogyny"
,"female infanticide"
,"female infanticides"
,"human trafficking"
,"forced prostitution"
,["equality", "sexual rights"]
,"reproductive rights"
,"divorce rights"
,"women's rights"
,"women rights"
,"women equal rights"
,"equal rights to all"
,"equal rights to men and women"
,"equality for men and women"
,"equality for women and men"
,"gender injustice"
,"gender injustices"
,"gender discrimination"
,"discrimination against female"
,"discrimination against all women"
,"discrimination against all girls"
,"discrimination against women"
,"discrimination against girls"
,"gender disparities"
,"gender gap"
,"female exploitation"
,"household equity"
,"female political participation"
,"women's underrepresentation"
,"women underrepresentation"
,"female entrepreneurship"
,"female ownership"
,"women's economic development"
,"women's power"
,"women economic development"
,"women power"
,"power to women"
,"gender-responsive budgeting"
,"gender quota"
,["foreign aid", "women's empowerment"]
,["foreign aid", "women empowerment"]
,"gender segregation"
,"gender-based violence"
,"gender based violence"
,"gender participation"
,"female politician"
,"female leader"
,"contraceptive behaviour"
,"women's autonomy"
,"women autonomy"
,"autonomy of women"
,"agrarian feminism"
,"microfinance"
,"women's livelihood"
,"women's ownership"
,"women livelihood"
,"women ownership"
,"female smallholder"
,"gender mainstreaming" 
])
        
    if cond1:
        return {"sdg_code": "sdg5", "sdg_label": "5. Gender equality"}
    return {}
